### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by ktimothy** [euank/node-noop#13]
I am so happy to finally meet such a useful npm module! But there is no license, so I do not know whether I am allowed to use node-noop in my commercial projects or not. Please add a license, it is very important.

**Comment by euank** [comment]
Sure, I'll add one. It was already listed as BSD 2-cluase in `package.json`, but you're right that the license text should be included in the repo. Thanks for reporting.

**Comment by ktimothy** [comment]
Thanks for quick fix! You are what call a real professional.
