### ISSUE TITLE
Test for global mutation insufficient

### ISSUE THREAD

**Issue by zapu** [euank/node-noop#14]
I'm not sure if this:

https://github.com/euank/node-noop/blob/master/test/test.js#L12-L16

is sufficient to test that `noop` did not mutate any state.

Does `assert.equal` do deep equality testing or does it just compare references? I'm afraid it is the latter.

Also even deep equality testing might be not enough. There may be objects that are not referenced in the `global` object, or things that are not accessible through node API to see if they have been changed or not (think pending setTimeout callbacks that might have been cancelled). I think we may eventually come up with some way of dumping internal node state, hashing that, and comparing before and after `noop` call.

**Comment by cookiengineer** [comment]
Maybe a test that uses a Proxy for the global object is necessary to keep track of mutations?

**Comment by euank** [comment]
Should be fixed in #6. If you've got a better way (e.g. via a proxy-object for global that fails on any get/set), PRs welcome.

**Comment by zapu** [comment]
I didn't notice that PR at the time of making my issue - my apologies! Thank you for merging the fix.
