### ISSUE TITLE
Is this package still maintained??

### ISSUE THREAD

**Issue by zeevl** [euank/node-noop#23]
No checkins in more than 3 months, dependencies are out of date, longstanding issues (3+ years) with no responses..   can we get some love here please??

**Comment by euank** [comment]
I believe this package is maintained at well above a level befitting the functionality it exposes.
If you would like either the package, or the maintainers of it, to do nothing in more ways, you're quite welcome to do something about it (like file issues). Or you could do nothing, that's cool too. I have some code that might be able to help you with that 'doing nothing' thing even.
